version: "3.9"

services:
  app:
    container_name: ${APP_CONTAINER_NAME:-react-app}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app/src:/app/src
    ports:
      - "${APP_PORT:-3000}:3000"
    tty: true
