version: "3.9"

services:
  app:
    container_name: ${PROD_APP_CONTAINER_NAME:-react-app-prod}
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
          - APP_FOLDER_NAME=${APP_FOLDER_NAME:-app}
    ports:
      - "${PROD_APP_PORT:-80}:80"
